### ISSUE TITLE
npm install requires multiple runs to complete installation

### ISSUE THREAD

**Issue by nlstrait** [hritikaggarwal2/husky-buddy#34]
Perhaps worth noting in your instructions: for me, I ran into two different errors when running `npm install` (neither of which I took any action to fix) before I successfully installed all packages. So, I had to run `npm install` three times in a row.

**Comment by hritikaggarwal2** [comment]
This is not something we can list in our documentation as it pertains to an incorrect node setup environment or a node error. Thus, this doesn't highlight how our application might be incorrectly set up or if we can otherwise fix this issue. But again this is a great catch (we have added this as a side note in the project). Thank you :)

**Comment by nlstrait** [comment]
You could at least mention that node needs to be installed and how to install or update so that the installation is "proper." You mention installing node dependencies but not node itself. It is your responsibility to document the tools you are using.
